[project]
name = "mlops-kasmakoli"
version = "0.1.0"
description = "Machine Learning Operations 02476"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "torch>=2.9.1",
]
