[project]
name = "mlops-kasmakoli"
version = "0.1.0"
description = "Machine Learning Operations 02476"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

